### ISSUE TITLE
Travis CI builds failing with "Job has been terminated due to insufficient credits balance"

### ISSUE THREAD

**Issue by chrisburr** [conda-forge/status#109]
Travis CI jobs are currently being killed with "Job has been terminated due to insufficient credits balance". We still have almost a million credits available so it's not clear why this is happening but it's under investigation.

**Comment by beckermr** [comment]
We're in contact with TravisCI and will update you all when we hear back from them.

**Comment by chrisburr** [comment]
Builds seem to be running again and I've restarted many of the cancelled builds. I'll leave this open while the backlog settles.

**Comment by chrisburr** [comment]
Looks like everything is caught up and stable again so I'll close this

**Comment by tkelman** [comment]
The fix didn't seem to last long, all the travis ppc64 builds started failing not long after with what looks like a resolver problem? See https://travis-ci.com/github/conda-forge/conda-forge-ci-setup-feedstock/builds/217635249 where some of the builds worked and some started failing, I think all travis builds since have failed with the same error.

**Comment by jakirkham** [comment]
That sounds like a different issue. Can you please raise a new issue? Perhaps on ( https://github.com/conda-forge/conda-forge-ci-setup-feedstock )?

**Comment by tkelman** [comment]
I'm not sure that issue is the cause, I just went through all the feedstocks that build on travis and found the first one to fail.

**Comment by isuruf** [comment]
It is. conda-forge-ci-setup for py36 and py37 succeeded and py38 and py39 failed due to this issue. We are trying to install that package into a python 3.8 environment and conda solver is going crazy trying to solve the environment. I marked py36 and py37 as broken, so check back in an hour and if not fixed, open an issue in https://github.com/conda-forge/conda-forge-ci-setup-feedstock

**Comment by tkelman** [comment]
Cool thanks for that, sorry for the wrong-place report.

**Comment by jakirkham** [comment]
No worries. Thanks for raising it. Also thanks Isuru for tracking that down 🙂
