### ISSUE TITLE
CDN mirroring down

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/status#179]
Currently CDN mirroring has not been running for a while. As a result packages that have been recently upgraded are not available yet

Have raised this issue upstream: https://github.com/conda/infrastructure/issues/942

**Comment by morremeyer** [comment]
We had an issue with a full disk, which our monitoring did not detect due to an edge case being triggered.

We have fixed the underlying issue and updated the monitoring to also detect this edge case.
The CDN sync is running again and we're monitoring it closely.

I will update this issue again once the sync has been successfully completed.

**Comment by jaimergp** [comment]
Thanks! Downgrading to "Degraded performance" now that the sync is in progress again.

**Comment by morremeyer** [comment]
The sync completed sucessfully and is running on schedule again.

**Comment by jaimergp** [comment]
Thanks @morremeyer!
